### ISSUE TITLE
Concern in Managing Platform-Specific Features

### ISSUE THREAD

**Issue by pinwhell** [gokhanettin/cmake-example#1]
I'm wondering how to address a concern I have. I have a "foo" and multiple conditional platform-specific "foos" (e.g., winFoo, LinuxFoo, or AndroidFoo), where all the platform-specific ones depend on the base "foo." I'm struggling with deciding whether to create a platform-agnostic "foo" and add platform-specific functionality conditionally within it. This approach would offer flexibility, but it means that if I include the platform-specific "foo," it won't have the base "foo" functionality, and attempting to add it could result in an unsightly circular dependency.

Alternatively, I'm considering having the platform-specific "foos" use the base agnostic "foo" and conditionally include them using "if-else" statements in all the places where they are needed. While this approach may work, it's not as flexible as I'd like, and I'm trying to find a balanced solution that offers flexibility while maintaining a smooth and elegant structure. What recommendations do you have?

**Comment by gokhanettin** [comment]
You would probably need an Operating System Abstraction Layer (OSAL). All the platform-specific code should go to this layer. Then, you can implement your `foo` on the top of it.

OSAL should provide a well-defined minimal API to `foo`. Consider the following folder structure:

```bash
.
CMakeLists.txt
app/
    app.c
    CMakeLists.txt
foo/
    foo.c
    foo.h
    CMakeLists.txt
osal/
    CMakeLists.txt
    linux/
        osal.c
        osal.h
        CMakeLists.txt
    win32/
         osal.c
         osal.h
         CMakeLists.txt        
```

Here are the basic sample CMakeLists.txt files:

```bash
$ cat ./CMakeLists.txt
cmake_minimum_required(VERSION 3.21)
project(ulak-n4g)

add_subdirectory(app)
add_subdirectory(foo)
add_subdirectory(osal)

$ cat app/CMakeLists.txt
add_executable(app
    app.c
)
target_link_libraries(app
   PRIVATE
   foo
)   

$ cat foo/CMakeLists.txt
add_library(foo
    foo.c
)
target_include_directories(foo
    PUBLIC
    "${CMAKE_CURRENT_SOURCE_DIR}"
)
target_link_libraries(foo
    PRIVATE
    osal
)

$ cat osal/CMakeLists.txt
if(WIN32)
    add_subdirectory(win32)
elseif(UNIX AND NOT APPLE)
    add_subdirectory(linux)
else()
   # And so on    
endif()

$ cat osal/win32/CMakeLists.txt
add_library(osal
    osal.c
)
target_include_directories(osal
    PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}"
)            
```

This is going generate `app`, `libfoo.a`, `libosal.a` where only the `libosal.a` depends on the platform you are targeting.
The dependency graph would look like app -> foo -> osal and `app` and `foo` would not know anything about the platform.

Note that once this method is applied properly, we don't even need to use any platform-specific conditional compilation within the source code.

**Comment by pinwhell** [comment]
```
target_link_libraries(foo
    PRIVATE
    osal
)
```

You're asking about linking "foo" to its platform-specific versions like "winFoo" or "androidFoo." However, say you want to test "winFoo" individually, you'll likely rely on "foo" itself, creating a circular dependency. How should this issue be addressed?

**Comment by gokhanettin** [comment]
I think we better go with a real example. Consider [DPDK's Environment Abstraction Layer(EAL)](https://github.com/DPDK/dpdk/tree/main/lib/eal). Please see how the eal interface within include directory is implemented for different operating systems and processor architectures.

You are going to implement a single foo based on multiple osals for each operating system. Let's say you are going to have a `foo_function` and it depends on `osal_function1`, `osal_function2` such that

```c
void foo_function(void) 
{
     bool ok = false;
    char* sys = osal_query_system();
    ok = osal_function1();
    if (!ok) {
        printf("foo_function is not supported on %s\n", sys);
        return;
    }
    osal_function2();
    
    // Some other code here.
    // osal is not a platform-specific version of foo. It knows nothing about foo.
    // It just abstracts away the operating system primitives to implement foo.
}
```

**Comment by pinwhell** [comment]
`OSAL is not a platform-specific version of 'foo'; it knows nothing about 'foo.'` I understand the OSAL you are explaining, and it seems like a suitable solution. However, something is still not clear to me. Is there no possibility to have a shared base, where multiple OSALs use the same function `bar`, which is platform-agnostic? Is there a way to share this functionality through a common base, perhaps in `foo`, allowing both OSALs to access it? If not, what could be an alternative approach? Should i consider creating another platform-agnostic library specifically for the `bar` functionality?

**Comment by gokhanettin** [comment]
I think creating another platform-agnostic library is a good choice. The dependecy graph now should look like app -> foo -> osal -> bar. You can also directly link and call `bar` from `foo` if you need to.

```cmake
target_link_libraries(osal
    PRIVATE
    bar
)
target_link_libraries(foo
    PRIVATE
    osal
    bar # If you need to call bar from foo
)
``` 


 We can't have the `bar` functionality within `foo` and call it from osals. That would create a circular dependency.

**Comment by pinwhell** [comment]
Thank you. I truly appreciate your amazing suggestions, they have been incredibly helpful.
